### PR TITLE
Fix issue with Pattern Whitespace

### PR DESCRIPTION
**Pull request by declanvk**
Fixes issue #254 

This change is [Reviewable](https://reviewable.io/reviews/open-i18n/rust-unic/253)

### CODE REVIEW

**Comment by CAD97** [comment]
...oops

bors: r+

**Comment by CAD97** [comment]
That'll teach me to wait for CI I suppose....

This is consistently failing on nightly only; I think there's a missing translation for this table in unic-gen.

cc @behnam directly: we're very wrong here and the fix is fairly straightforward but apparently not this trivial. The earliest I could possibly look at it is Saturday.

**Comment by behnam** [comment]
bors: r+

**Comment by behnam** [comment]
Thanks, @declanvk, for catching this and sending the fix!

**Comment by behnam** [comment]
bors: r-

**Comment by behnam** [comment]
Needed a change. Trying to fix it in https://github.com/open-i18n/rust-unic/pull/255 . Thanks all!

**Pull request closed without merging**
